sports_store/accounts/api/urls.py
from django.urls import path
from accounts.api import views

from rest_framework.authtoken.views import obtain_auth_token

app_name = 'accounts'

urlpatterns = [
    path('login/', obtain_auth_token, name='login'),
    path('logout/', views.LogoutAPIView.as_view(), name='logout'),
    path('register/', views.CreateUserView.as_view(), name='create_user'),
]

sports_store/base/api/urls.py
from django.urls import path

from base.api import views

app_name = 'base'

urlpatterns = [
    # Brand
    path('brand/', views.BrandListView.as_view(), name='brandlist'),
    path('brand/<int:pk>/', views.BrandDetailView.as_view(), name='branddetail'),
    
    # Category
    path('category/', views.CategoryListView.as_view(), name='categorylist'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='categorydetail'),
    
    # Product
    path('product/', views.ProductListView.as_view(), name='productlist'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='productdetail'),
    
    # Increase quantity
    path('product/<int:pk>/increase_quantity/', views.AddProductQuantityView.as_view(), name='increase_quantity'),
]

sports_store/shop_cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, remove_from_cart, clear_cart

app_name = 'shop_cart'

urlpatterns = [
    path('cart_detail/', cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('cart/clear/', clear_cart, name='clear_cart'),
]

sports_store/sports_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.api.urls')),
    path('', include('base.api.urls')),
    path('cart/', include('shop_cart.api.urls')),
    path("pay/", include('payment.api.urls')),
] 
  

sports_store/base/models.py
from django.db import models

# Create your models here.

class Brand(models.Model):
    brand_name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.brand_name
    

class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.category_name
    

class Product(models.Model):
    
    SIZE_CHOICES = [
        ('Extra Small', 'XS'),
        ('Small', 'S'),
        ('Medium', 'M'),
        ('Large', 'L'),
        ('Extra Large', 'XL'),
    ]
    
    product_name = models.CharField(max_length=100)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, default=None, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=100, choices=SIZE_CHOICES)
    quantity = models.BigIntegerField(default=1, null=True)
    
    def __str__(self):
        return self.product_name
    
            
    

sports_store/base/forms.py
from typing import Any
from django import forms

from base.models import Brand, Category, Product


class BrandForm(forms.ModelForm):
    brand_name = forms.CharField(
        max_length=100,
        label='Brand Name',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Brand Name'}
    ))
    
    class Meta:
        model = Brand
        fields = ['brand_name']
        
    def clean_name(self):
        name = self.cleaned_data.get('brand_name')
        if Brand.objects.filter(brand_name=name).exists():
            raise forms.ValidationError('Brand name already exists.')
        return name
    
    
class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category
        fields = ['category_name']
        
    def clean_name(self):
        name = self.cleaned_data.get('category_name')
        if Category.objects.filter(category_name=name).exists():
            raise forms.ValidationError('Category name already exists.')
        return name
    
    
class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = '__all__'
        
    
class IncreaseProductForm(forms.ModelForm):
    
    # amount = forms.IntegerField(label='Amount', help_text='Enter a positive number')
    
    class Meta:
        model = Product
        fields = ['quantity',]
        
    def clean_quantity(self):
        quantity = self.cleaned_data.get('quantity')
        if quantity <= 0:
            raise forms.ValidationError('Quantity must be a positive number.')
        return quantity
        
    # def __init__(self, *args, **kwargs):
    #     super(IncreaseProductForm, self).__init__(*args, **kwargs)
    #     self.fields['quantity'].widget.attrs['readonly'] = True

sports_store/base/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions, status, generics

from base.api.serializers import *

from django.shortcuts import get_object_or_404


# class BrandListView(APIView):
    
    # def get(self, request):
    #     # Implement logic to retrieve all brands
    #     brands = Brand.objects.all()
    #     serializer = BrandSerializer(brands, many=True)
    #     return Response(serializer.data)
    
    # def post(self, request):
    #     # Implement logic to create a new brand
    #     serializer = BrandSerializer(data=request.data)
    #     if serializer.is_valid():
    #         serializer.save()
    #         return Response(serializer.data, status=status.HTTP_200_OK)
    #     else:
    #         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
# Brand
class BrandListView(generics.ListCreateAPIView):
    queryset = Brand.objects.all()
    serializer_class = BrandSerializer
        
    
class BrandDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Brand.objects.all()
    serializer_class = BrandSerializer
    
    
# Category 
class CategoryListView(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

    
class CategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    
    
# Product
class ProductListView(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    

class ProductDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class AddProductQuantityView(APIView):
    
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        serializer = AddProductQuantitySerializer(data=request.data)
        if serializer.is_valid():
            quantity = serializer.validated_data['quantity']
            product.quantity += quantity
            product.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

sports_store/base/views.py
from django.shortcuts import render, redirect

from base.filter import ProductFilter, BrandFilter

from base.forms import BrandForm, CategoryForm, ProductForm, IncreaseProductForm
from base.models import Product, Category, Brand

from django.shortcuts import render, get_object_or_404

# Create your views here.

def home(request):
    products = Product.objects.all()
    brand = Brand.objects.all()
    
    myFilter = ProductFilter(request.GET, queryset=products)
    brand = myFilter.qs
    
    return render(request, 'base/home.html', {
        'brand': brand,
        'products': products,
        'myFilter': myFilter
        })
    
    
def most_viewed_products(request):
    most_viewed = Product.objects.order_by('-views')[:5]
    return render(request, 'base/home.html', {'most_viewed': most_viewed})
    

def filter_by_brand(request,brand_name):
    brand = get_object_or_404(Brand, brand_name=brand_name)
    products = Product.objects.filter(brand=brand)
    categories = Category.objects.all()
    category_id = request.GET.get('category')
    
    selected_category = None
    if category_id:
        selected_category = get_object_or_404(Category, id=category_id)
        products = Product.objects.filter(category=selected_category, brand=brand)
    
    return render(request, 'base/brand_products.html', {
        'brand': brand,
        'products': products,
        'selected_category': selected_category,
        'categories': categories,
        })
    
    
def single_product_view(request, product_id, brand_name):
    brand = get_object_or_404(Brand, brand_name=brand_name)
    single_product = get_object_or_404(Product, brand=brand, pk=product_id)
    
    category = single_product.category
    
    related_products = Product.objects.filter(category=category).exclude(pk=product_id)[:3]
    other_products = Product.objects.all().exclude(pk=product_id)[:3]
    
    return render(request, 'base/single_product.html', {
        'single_product': single_product,
        'related_products': related_products,
        'other_products': other_products})
     


def add_brand(request):
    if request.method == 'POST':
        form = BrandForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('base:add_product')
    else:
        form = BrandForm()
    return render(request, 'base/add_brand.html', {'form': form})


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('base:add_product')
        else:
            print(form.errors)
    else:
        form = CategoryForm()
    return render(request, 'base/add_category.html', {'form': form})


def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('base:home')
    else:
        form = ProductForm()
    return render(request, 'base/add_product.html', {'form': form})
        
    
def increase_quantity(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        form = IncreaseProductForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            if quantity == None:
                quantity = 1
                product.quantity += quantity
                product.save()
            else:
                product.quantity += quantity
                product.save()
            return redirect('base:product', product_id=product.id, brand_name=product.brand.brand_name)
    else:
        form = IncreaseProductForm(instance=product)
    return render(request, 'base/increase_quantity.html', {'form': form,
                                                           'product': product})

sports_store/base/templates/base/add_brand.html
{% extends "base/home.html" %}

    {% block title %} | Add Brand {% endblock %}

    {% block content %}
<body>

    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Brand</button>
        </form>
    </div>
    
    
</body>
    {% endblock %}

sports_store/base/templates/base/add_category.html
{% extends "base/home.html" %}
    {% block title %} | Add Category {% endblock %}

    {% block content %}
<body>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Category</button>
    </form>
    
</body>
    {% endblock %}

sports_store/base/templates/base/add_product.html
{% extends "base/home.html" %}
    <title>Add product</title>

    {% block content %}
    <body>

    <h1>Add Product</h1>

    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="pname">Product name:</label>
            {{ form.product_name }}
        </div>
        <br>
        
        <div class="form-group">
            <label for="price">Price:</label>
            {{ form.price }}
        </div>
        <br>

        <div class="form-grouo">
            <label for="category">Category:</label>
            {{ form.category }}
            <br>
            <p>If category does not exist: <a href="{% url 'base:add_category' %}">Add Category</a></p>
        </div>
        <br>

        <div class="form-grouo">
            <label for="brand">Brand:</label>
            {{ form.brand }}
            <br>
            <p>If Brand does not exist: <a href="{% url 'base:add_brand' %}">Add Brand</a></p>
        </div>
        <br>

        <div class="form-group">
            <label for="size">Size:</label>
            {{ form.size }}
        </div>
        <br>

        <div class="form-group">
            <label for="quantity">Quantity:</label>
            {{ form.quantity }}
        </div>
        <br>

        
        <button type="submit">Add product</button>
    </form>
    
</body>
    {% endblock %}
    

sports_store/base/templates/base/brand_products.html
{% extends "base/home.html" %}


    <title> |{{ brand.brand_name }}</title>
    
<body>
    {% block content %}
    <div class="container">
        <h1>Products of {{ brand.brand_name }}</h1>

        <form method="get" action="{% url 'base:brand' brand.brand_name %}">
            <div class="form-group">
                <label for="category">Filter by Category:</label>
                <select class="form-control" id="" name="category">
                    <option value="">All Categories</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}" {% if category == selected_category %}selected{% endif %}>
                            {{ category.category_name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>

        <hr>

    {% if products %}

        {% for p in products %}

            <ul>
                <li><a href="{% url 'base:product' p.brand p.id %}">{{ p.product_name }}</a></li>
            </ul>
        {% endfor %}
    
    {% else %}
        <p>No products found for this brand.</p>
        {% if user.is_superuser %}
        <a href="{% url 'base:add_product' %}">Add a product</a>
        {% endif %}
    {% endif %}

    
</body>

{% endblock %}

sports_store/base/templates/base/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Home{% block title %} {% endblock %}</title>
</head>

<body>


    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'base:home' %}">Brand</a>
            </div>

            <form class="navbar-form navbar-left">
                <div class="form-group">
                    {% csrf_token %}
                    {{myFilter.form}}
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_superuser %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                        aria-expanded="false">
                        Admin Center <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'base:add_product' %}">Add new product</a></li>
                        <li><a href="{% url 'base:add_category' %}">Add new Category</a></li>
                        <li><a href="{% url 'base:add_brand' %}">Add new Brand</a></li>
                    </ul>
                </li>
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                        aria-expanded="false">
                        {% if user.is_authenticated %}
                        {{ user.username }}
                        {% else %}
                        Login/Sign Up
                        {% endif %}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        <li><a href="{% url 'accounts:change_details' %}">Change Details</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:create_user' %}">Sign Up</a></li>
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        {% endif %}
                    </ul>

                </li>
            </ul>
            <a href="{% url 'shop_cart:cart_detail' %}">Cart</a>
        </div>
    </nav>



    {% block content %}

    <div class="container-fluid">
        <div class="jumbotron">
            <h1> Welcome to the Online Store </h1>

            <h3>You are logged on as an admin</h3>
            <ol>

            </ol>
        </div>

        <h3>All Brands</h3>
        {% for b in brand %}
        <ul>
            <li><a href="{% url 'base:brand' b.brand.brand_name %}">{{ b.brand.brand_name }}</a></li>
        </ul>
        {% endfor %}
        {% endblock %}
    </div>

    <!-- <h3>Current products</h3>
        {% for p in products %}
        <ul>
            <li>
                <a href="{% url 'base:product' p.brand.brand_name p.id %}">
                    {{ p.product_name }}-{{ p.brand.brand_name}} - &pound;{{ p.price}}
                </a>
            </li>
        </ul>
        {% endfor %} -->


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>

sports_store/base/templates/base/increase_quantity.html
{% extends "base/home.html" %}

{% block title %} | Add quantity {% endblock  %}

{% block content %}

<h1>Update Quantity for {{product.brand.brand_name}} | {{ product.product_name }}</h1>
<form action="" method="post">
    {% csrf_token %}
    <p>Current Quantity: {{ form.quantity.value }}</p>
    {{ form.as_p }}
    <button type="submit">Add</button>
</form>

{% endblock %}

sports_store/base/templates/base/single_product.html
{% extends "base/home.html" %}

{% block title %} | {{ single_product.product_name }} {% endblock %}

{% block content %}

<div class="container">
<h1>{{ single_product.brand }} | {{ single_product.product_name }}</h1>

<p>Size: {{ single_product.size }}</p>
<p>Price: &pound{{ single_product.price }}</p>
<p> Brand: {{ single_product.brand}}</p>

{% if single_product.quantity is not None %}
<p> Available: {{ single_product.quantity }}</p>
<a href=""><button type="button">Buy now</button></a>
<a href="{% url 'shop_cart:add_to_cart' single_product.id %}"><button type="button">Add to cart</button></a>
{% else %}
    <p>Out of stock</p>
{% endif %}

{% if user.is_superuser %}
<a href="{% url 'base:add_quantity' single_product.id%}"><button type="button">Add quantity</button></a>
{% endif %}
<br>
<br>

{% if related_products %}
<h3>Related products</h3>
{% for p in related_products %}
<p>{{ p.product_name }}</p>
{% endfor %}
{% else %}
<h2>Other products you may like</h3>
{% for o in other_products %}

<a href="{% url 'base:product' o.brand o.id %}"><p>{{ o.product_name }}</p></a>
{% endfor %}
{% endif%}

</div>

{% endblock %}